branches:
    only:
        - master

stages:
    - name: go-pb-update
      if: type = push
    - name: test

matrix:
    include:
        - language: go
          stage: go-pb-update
          go: master
          sudo: true
          services:
              - docker
          install:
              - docker pull $DOCKER_AUX_REPO
              - go get -u github.com/gogo/protobuf/protoc-gen-gofast
          script: bash -v ci/go-pb-update.sh

        - language: go
          stage: test
          go: 1.9.x
        - language: go
          go: 1.10.x
          install:
              - go get golang.org/x/tools/cmd/cover
              - go get -t ./...
          script: go test -v -race -covermode=atomic -coverprofile=coverage.txt
          after_success: bash <(curl -s https://codecov.io/bash)
        - language: go
          go: master

    sudo: false
